platform :ios, '8.0'

target 'AirMoPub' do
	pod 'mopub-ios-sdk', '4.15.0'
	pod 'AdColony', '3.1.1'
	pod 'ChartboostSDK', '6.6.3'
	pod 'FBAudienceNetwork', '4.23.0'
	pod 'Firebase/AdMob', '4.0.2'
	pod 'SupersonicSDK', '6.4.19.1'
	pod 'TapjoySDK', '11.9.0'
	pod 'UnityAds', '2.1.0'
	pod 'VungleSDK-iOS', '4.1.0'
end

